version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.23.0
  - dependency-name: danger
    versions:
    - 10.6.4
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
    - 12.1.1
  - dependency-name: socket.io
    versions:
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: husky
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@seadub/danger-plugin-junit"
    versions:
    - 0.2.0
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
